### PR TITLE
Titles should be <h3> on subchapter views

### PR DESCRIPTION
**Pull request by cynmij**

### CODE REVIEW

**Comment by cynmij** [comment]
CSS for views-row-lines takes care of https://stanfordits.atlassian.net/browse/FH16-49

**Comment by cynmij** [comment]
Last commit on this branch for the VBO: https://stanfordits.atlassian.net/browse/FH16-47

**Comment by jbickar** [comment]
Look at `handbooks/faculty-handbook` for the `.views-row-lines` and `handbooks/faculty-handbook/chapter-1/subchapter-1` for the h3s

**Comment by jbickar** [comment]
Nice work. Thanks!

**Pull request merged**
